library(DESeq2)
library(RColorBrewer)
library(pheatmap)
library(tidyverse)
library(dplyr)

# counts.csv was generated by 01_download_data.R
counts_data <- read.csv("data/counts.csv", header = TRUE, row.names = 1, check.names = FALSE)

# sample_metadata.csv contains condition info (Old/AD) per sample
col.data <- read.csv("data/sample_metadata.csv", header = TRUE, row.names = "srr")

# Keep the original SRR accession as a column before renaming
col.data$srr_accession <- rownames(col.data)

# Rename samples for readability (SRR accessions → condition_replicate)
new_names <- c("Old_1", "Old_2", "Old_3", "AD_1", "AD_2", "AD_3")

colnames(counts_data) <- new_names
rownames(col.data) <- new_names

# sanity check: names match and are in the same order
all(colnames(counts_data) == rownames(col.data))

# sanity check: SRR values preserved correctly
col.data[, c("srr_accession", "condition")]

# Build the DESeq2 dataset object
data.dds <- DESeqDataSetFromMatrix(countData = counts_data,
                                   colData = col.data,
                                   design = ~ condition)
data.dds

# Filter out low-count genes (rows summing less than 10 across all samples may be noise)
keep <- rowSums(counts(data.dds)) >= 10
data.ddsk <- data.dds[keep, ]

# Set factor level: important because otherwise DESeq2 uses whichever level
# comes first alphabetically as reference — here, that's Old (correct default,
# but set explicitly for clarity)
data.ddsk$condition <- relevel(data.ddsk$condition, ref = "Old")

# Run DESeq2
data.analisis <- DESeq(data.ddsk)
res_data <- results(data.analisis)
res_data

plotDispEsts(data.analisis)

# n=3/group: higher outlier % than usual is expected (Cook's distance is 
# more sensitive with small n), not a pipeline error
summary(res_data)

# Shrink log2FoldChange estimates to correct for genes with low counts/high 
# dispersion, which otherwise show artificially inflated fold changes
resultsNames(data.analisis)  # check the exact coefficient name
res_data <- lfcShrink(data.analisis, coef = 2, type = "apeglm")

# Normalize and estimate size factors
estimated_data.dds <- estimateSizeFactors(data.ddsk)
sizeFactors(estimated_data.dds)
normalized_data <- counts(estimated_data.dds, normalized = TRUE)
View(normalized_data)

# Variance stabilizing transformation
vsd_data <- vst(estimated_data.dds, blind = TRUE)
vsd_mat_data <- assay(vsd_data)

# Sample-to-sample correlation
vsd_cor_data <- cor(vsd_mat_data)
View(vsd_cor_data)

# PCA plot
pca_data <- plotPCA(vsd_data, intgroup = "condition", returnData = TRUE)
percentVar <- round(100 * attr(pca_data, "percentVar"))

ggplot(pca_data, aes(x = PC1, y = PC2, color = condition)) +
  geom_point(size = 5) +
  xlab(paste0("PC1: ", percentVar[1], "% variance")) +
  ylab(paste0("PC2: ", percentVar[2], "% variance"))

# Scree plot: run PCA on the same VST-transformed matrix used above
# (not raw counts_data, since PCA on unnormalized counts is dominated by
# sequencing depth rather than biological variance)
PCA_2 <- prcomp(t(vsd_mat_data), scale = TRUE)
names(PCA_2)

prop_variance <- PCA_2$sdev^2 / sum(PCA_2$sdev^2)
prop_variance

ggplot(data = data.frame(prop_variance, pc = 1:length(prop_variance)), aes(x = pc, y = prop_variance)) +
  geom_col(fill = "red", color = "red", width = 0.5) +
  scale_y_continuous(limits = c(0, 1)) +
  labs(x = "Principal components", y = "Proportion of variance explained")

# Note: despite PC1+PC2 explaining >50% of variance, they do not show clean 
# separation between Old and AD groups. This suggests other sources of 
# variability (individual donor differences, technical variation) may 
# dominate over disease status in this small, matched subset (n=3/group).


# Sample-to-sample correlation heatmap
pheatmap(vsd_cor_data)

# Save DESeq2 results object for use in 03_volcano_plot.R
saveRDS(res_data, "data/res_data.rds")

