library(DESeq2)
library(dplyr)
library(ggplot2)
library(org.Hs.eg.db)

# Load DESeq2 results object generated by 02_qc.R
res_data <- readRDS("data/res_data.rds")

res_table <- as.data.frame(res_data)
res_table <- tibble::rownames_to_column(res_table, "gene_id")
nrow(res_table)

# Flag significant genes
res_table <- dplyr::mutate(res_table, sig = ifelse((res_table$padj < 0.1) & (abs(res_table$log2FoldChange) > 2), "yes", "no"))

res_table_sig <- res_table %>% filter(sig == "yes")
nrow(res_table_sig)

# Strip Ensembl version suffix (e.g. ".15") — recount3/GENCODE IDs include 
# it, but org.Hs.eg.db expects unversioned Ensembl IDs
res_table_sig$gene_id_clean <- sub("\\..*", "", res_table_sig$gene_id)

# Map Ensembl IDs to gene symbols
res_table_sig$gene_name <- mapIds(org.Hs.eg.db, 
                                  keys = res_table_sig$gene_id_clean, 
                                  keytype = "ENSEMBL", 
                                  column = "SYMBOL")

res_table <- res_table[order(abs(res_table$log2FoldChange), decreasing = TRUE), ]

# Classify genes by direction of change
res_table <- res_table %>% 
  mutate(Expression = case_when(
    log2FoldChange >= 2 & padj <= 0.1 ~ "Up-regulated",
    log2FoldChange <= -2 & padj <= 0.1 ~ "Down-regulated",
    TRUE ~ "Unchanged"
  ))

table(res_table$Expression)

# Save significant genes table for 04_heatmap.R
saveRDS(res_table_sig, "data/res_table_sig.rds")

# Map gene symbols for the top significant genes (for plot labels)
top_genes <- res_table %>%
  filter(Expression != "Unchanged") %>%
  arrange(padj) %>%
  head(15)

top_genes$gene_id_clean <- sub("\\..*", "", top_genes$gene_id)
top_genes$gene_name <- mapIds(org.Hs.eg.db, 
                              keys = top_genes$gene_id_clean, 
                              keytype = "ENSEMBL", 
                              column = "SYMBOL")

res_table <- left_join(res_table, top_genes[, c("gene_id", "gene_name")], by = "gene_id")

# Volcano plot
p <- ggplot(res_table, aes(log2FoldChange, -log10(padj))) + 
  geom_point(aes(col = Expression)) + 
  scale_color_manual(values = c("darkturquoise", "grey25", "darkorange")) +
  geom_vline(xintercept = -2, colour = "grey", linetype = "dotted", linewidth = 0.5) +
  geom_vline(xintercept = 2, colour = "grey", linetype = "dotted", linewidth = 0.5) +
  geom_hline(yintercept = 1, colour = "grey", linetype = "dotted", linewidth = 0.5) +
  xlim(-5, 12) +
  theme_bw() +
  theme(legend.position = "top")
p1 <- p + geom_text(aes(label = gene_name), size = 3, nudge_y = 0.6, check_overlap = TRUE)
p1


